# Define a Role with permissions to get and list secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ebs-csi-secret-access
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
# Bind the Role to the EBS CSI driver's ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ebs-csi-secret-access-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ebs-csi-secret-access
subjects:
  - kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system

